[package]
name = "hematite"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.7.4", features = ["http1", "http2", "tokio"] }
axum-macros = "0.4.1"
cloudevents-sdk = "0.7.0"
dashmap = "5.5.3"
data-encoding = "2.4.0"
jsonwebtoken = { version = "9.2.0", features = ["use_pem"] }
log = "0.4.21"
opentelemetry-otlp = { version = "0.15.0", features = ["logs", "metrics"] }
opentelemetry_api = { version = "0.20.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
rand = "0.8.5"
reqwest = { version = "0.11.26", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.114"
shadow-rs = "0.27.1"
thiserror = "1.0.58"
time = "0.3.34"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "fs"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"
uuid = { version = "1.8.0", features = ["serde", "v7"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
shadow-rs = "0.27.1"

[[bench]]
name = "write_benchmark"
harness = false

[[bench]]
name = "read_benchmark"
harness = false
