version: "3.2"
services:
  jaeger-all-in-one:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP protobuf receiver

