# fly.toml app configuration file generated for hematitedb on 2024-01-23T08:22:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hematitedb"
primary_region = "ord"

[build]

[env]
  # The trailing slash on OIDC_URL is important!
  HEMATITE_OIDC_URL = "https://96lo74.logto.app/oidc/"
  HEMATITE_JWT_AUD = "https://hematitedb.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "streams"
  destination = "/var/lib/hematite/streams"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
